name: Android Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Validate API Key
        run: |
          if [ -z "${{ secrets.API_KEY }}" ]; then
            echo "Error: API_KEY secret is not set"
            exit 1
          fi
          echo "API Key is present"

      - name: Create .env file
        run: |
          mkdir -p assets
          echo "API_KEY=${{ secrets.API_KEY }}" > assets/.env
          echo "Verifying .env file contents:"
          cat assets/.env
          if [ ! -s assets/.env ]; then
            echo "Error: .env file is empty"
            exit 1
          fi

      - name: Debug directory structure
        run: |
          ls -la
          ls -la assets/
          cat assets/.env

      - name: Build APK
        run: |
          flutter build apk --release --verbose
          ls -la build/app/outputs/flutter-apk/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 